# Generated by Django 2.2 on 2020-08-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_orders_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderProducts', to='webapp.Product', verbose_name='Номер заказа'),
        ),
    ]
